/**
 * \file StubApis.cpp
 * \brief Clean stubs for the out-of-scope host-API families (FR-009/US5):
 *        Bluetooth, GPIO/PWM/ADC/I2C/SAO, pixel strip, USB CDC and
 *        badge-to-badge messaging. Every call returns the defined
 *        "unavailable" contract (HOST_ERR_NOT_SUPPORTED or a neutral
 *        value) and logs once per symbol, so plugins degrade gracefully
 *        and the emulator never crashes.
 *
 * GENERATED by scratchpad gen_stubs.py from host_api.h - regenerate after
 * a host-API level bump instead of editing by hand.
 */
#include "cdc_log.h"
#include "plugin_manager/host_api.h"

namespace {

void logUnavailable(const char* symbol)
{
    // One log line per symbol per run keeps scripted output readable.
    LOG_W("HostStub", "%s: unavailable in the emulator (out-of-scope family)",
          symbol);
}

#define STUB_ONCE(symbol)                                                      \
    do {                                                                       \
        static bool warned = false;                                            \
        if (!warned) {                                                         \
            warned = true;                                                     \
            logUnavailable(symbol);                                            \
        }                                                                      \
    } while (0)

}  // namespace

extern "C" {

bool host_ble_is_enabled(void)
{
    STUB_ONCE("host_ble_is_enabled");
    return false;
}

int host_ble_mac(uint8_t out[6])
{
    (void)out;
    STUB_ONCE("host_ble_mac");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_device_name(char* out, size_t out_size)
{
    (void)out;
    (void)out_size;
    STUB_ONCE("host_ble_device_name");
    return HOST_ERR_NOT_SUPPORTED;
}

int8_t host_ble_rssi(void)
{
    STUB_ONCE("host_ble_rssi");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_register_service(ble_service_def_t* def, ble_char_def_t* chars, uint32_t num_chars)
{
    (void)def;
    (void)chars;
    (void)num_chars;
    STUB_ONCE("host_ble_register_service");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_unregister_service(uint32_t service_handle)
{
    (void)service_handle;
    STUB_ONCE("host_ble_unregister_service");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_send_notification(uint32_t char_handle, const uint8_t* data, size_t len)
{
    (void)char_handle;
    (void)data;
    (void)len;
    STUB_ONCE("host_ble_send_notification");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_send_indication(uint32_t char_handle, const uint8_t* data, size_t len)
{
    (void)char_handle;
    (void)data;
    (void)len;
    STUB_ONCE("host_ble_send_indication");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_consume_write(uint32_t char_handle, uint8_t* buf, size_t buf_size)
{
    (void)char_handle;
    (void)buf;
    (void)buf_size;
    STUB_ONCE("host_ble_consume_write");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_scan_start(uint32_t duration_ms)
{
    (void)duration_ms;
    STUB_ONCE("host_ble_scan_start");
    return HOST_ERR_NOT_SUPPORTED;
}

bool host_ble_scan_done(void)
{
    STUB_ONCE("host_ble_scan_done");
    return false;
}

int host_ble_scan_results(ble_scan_result_t* out, size_t* count)
{
    (void)out;
    (void)count;
    STUB_ONCE("host_ble_scan_results");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_connect(const uint8_t addr[6], uint8_t addr_type)
{
    (void)addr;
    (void)addr_type;
    STUB_ONCE("host_ble_connect");
    return HOST_ERR_NOT_SUPPORTED;
}

uint32_t host_ble_conn_handle(void)
{
    STUB_ONCE("host_ble_conn_handle");
    return 0;
}

int host_ble_disconnect(uint32_t conn)
{
    (void)conn;
    STUB_ONCE("host_ble_disconnect");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_discover(uint32_t conn, const uint8_t uuid[16], uint32_t action_id)
{
    (void)conn;
    (void)uuid;
    (void)action_id;
    STUB_ONCE("host_ble_discover");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_consume_discovery(ble_remote_char_t* out, size_t* count)
{
    (void)out;
    (void)count;
    STUB_ONCE("host_ble_consume_discovery");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_read_char(uint32_t conn, uint16_t value_handle, uint32_t action_id)
{
    (void)conn;
    (void)value_handle;
    (void)action_id;
    STUB_ONCE("host_ble_read_char");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_consume_read(uint8_t* buf, size_t buf_size)
{
    (void)buf;
    (void)buf_size;
    STUB_ONCE("host_ble_consume_read");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_write_char(uint32_t conn, uint16_t value_handle, const uint8_t* data, size_t len, uint8_t with_response)
{
    (void)conn;
    (void)value_handle;
    (void)data;
    (void)len;
    (void)with_response;
    STUB_ONCE("host_ble_write_char");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_subscribe(uint32_t conn, uint16_t cccd_handle, uint32_t action_id)
{
    (void)conn;
    (void)cccd_handle;
    (void)action_id;
    STUB_ONCE("host_ble_subscribe");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_ble_consume_notification(uint16_t* value_handle_out, uint8_t* buf, size_t buf_size)
{
    (void)value_handle_out;
    (void)buf;
    (void)buf_size;
    STUB_ONCE("host_ble_consume_notification");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_usb_cdc_write(const uint8_t* data, size_t len)
{
    (void)data;
    (void)len;
    STUB_ONCE("host_usb_cdc_write");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_gpio_set_direction(uint8_t pin, uint8_t direction)
{
    (void)pin;
    (void)direction;
    STUB_ONCE("host_gpio_set_direction");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_gpio_set_pull(uint8_t pin, uint8_t pull)
{
    (void)pin;
    (void)pull;
    STUB_ONCE("host_gpio_set_pull");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_gpio_write(uint8_t pin, bool level)
{
    (void)pin;
    (void)level;
    STUB_ONCE("host_gpio_write");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_gpio_read(uint8_t pin, bool* level)
{
    (void)pin;
    (void)level;
    STUB_ONCE("host_gpio_read");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_gpio_release(uint8_t pin)
{
    (void)pin;
    STUB_ONCE("host_gpio_release");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_gpio_pwm_start(uint8_t pin, uint32_t freq_hz, uint16_t duty_per_mille)
{
    (void)pin;
    (void)freq_hz;
    (void)duty_per_mille;
    STUB_ONCE("host_gpio_pwm_start");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_gpio_pwm_set_duty(uint8_t pin, uint16_t duty_per_mille)
{
    (void)pin;
    (void)duty_per_mille;
    STUB_ONCE("host_gpio_pwm_set_duty");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_gpio_pwm_stop(uint8_t pin)
{
    (void)pin;
    STUB_ONCE("host_gpio_pwm_stop");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_adc_read(uint8_t pin, uint16_t* raw, uint16_t* millivolt)
{
    (void)pin;
    (void)raw;
    (void)millivolt;
    STUB_ONCE("host_adc_read");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_i2c_write(uint8_t bus, uint8_t addr, const uint8_t* data, size_t len)
{
    (void)bus;
    (void)addr;
    (void)data;
    (void)len;
    STUB_ONCE("host_i2c_write");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_i2c_read(uint8_t bus, uint8_t addr, uint8_t* data, size_t len)
{
    (void)bus;
    (void)addr;
    (void)data;
    (void)len;
    STUB_ONCE("host_i2c_read");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_i2c_write_read(uint8_t bus, uint8_t addr, const uint8_t* wr, size_t wr_len, uint8_t* rd, size_t rd_len)
{
    (void)bus;
    (void)addr;
    (void)wr;
    (void)wr_len;
    (void)rd;
    (void)rd_len;
    STUB_ONCE("host_i2c_write_read");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_i2c_scan(uint8_t bus, uint8_t* found_addrs, size_t* count)
{
    (void)bus;
    (void)found_addrs;
    (void)count;
    STUB_ONCE("host_i2c_scan");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_sao_eeprom_read(uint16_t offset, uint8_t* buf, size_t len)
{
    (void)offset;
    (void)buf;
    (void)len;
    STUB_ONCE("host_sao_eeprom_read");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_sao_eeprom_write(uint16_t offset, const uint8_t* buf, size_t len)
{
    (void)offset;
    (void)buf;
    (void)len;
    STUB_ONCE("host_sao_eeprom_write");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_pixel_strip_init(uint8_t gpio_pin, uint16_t num_pixels, uint8_t format)
{
    (void)gpio_pin;
    (void)num_pixels;
    (void)format;
    STUB_ONCE("host_pixel_strip_init");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_pixel_strip_deinit(void)
{
    STUB_ONCE("host_pixel_strip_deinit");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_pixel_strip_set(uint16_t index, uint8_t r, uint8_t g, uint8_t b)
{
    (void)index;
    (void)r;
    (void)g;
    (void)b;
    STUB_ONCE("host_pixel_strip_set");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_pixel_strip_fill(uint8_t r, uint8_t g, uint8_t b)
{
    (void)r;
    (void)g;
    (void)b;
    STUB_ONCE("host_pixel_strip_fill");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_pixel_strip_clear(void)
{
    STUB_ONCE("host_pixel_strip_clear");
    return HOST_ERR_NOT_SUPPORTED;
}

int host_pixel_strip_refresh(void)
{
    STUB_ONCE("host_pixel_strip_refresh");
    return HOST_ERR_NOT_SUPPORTED;
}

uint16_t host_pixel_strip_length(void)
{
    STUB_ONCE("host_pixel_strip_length");
    return 0;
}

bool host_pixel_strip_ready(void)
{
    STUB_ONCE("host_pixel_strip_ready");
    return false;
}

}  // extern "C"
